from __future__ import annotations

from typing import Any

ADDITIONAL_EVIDENCE_TABLES: dict[str, dict[str, Any]] = {
    "host_filter_profiles": {
        "dataset_keys": ("host_filter_profiles", "host_filter_profile_evidence"),
        "record_type": "host_filter_profile",
        "fts_type": "host_filter_profiles",
        "columns": ("profile_id", "name", "access_mode", "time_budget", "blocked", "devices_json", "source"),
        "record_key_fields": ("profile_id", "name", "source"),
        "sort": "COALESCE(t.name, '')",
        "time_column": "",
        "note": "Host filter/profile evidence parsed from FRITZ!Box read-only state.",
    },
    "mesh_topology_links": {
        "dataset_keys": ("mesh_topology_links", "mesh_links"),
        "record_type": "mesh_topology_link",
        "fts_type": "mesh_topology_links",
        "columns": (
            "node",
            "node_mac",
            "interface",
            "peer",
            "peer_mac",
            "link_type",
            "state",
            "last_connected",
            "rx",
            "tx",
            "source",
        ),
        "record_key_fields": ("node_mac", "interface", "peer_mac", "link_type", "source"),
        "sort": "COALESCE(t.last_connected, '')",
        "time_column": "last_connected",
        "note": "Mesh topology link parsed from FRITZ!Box mesh topology evidence.",
    },
    "wan_port_mappings": {
        "dataset_keys": ("wan_port_mappings", "wan_exposure", "port_mappings"),
        "record_type": "wan_port_mapping",
        "fts_type": "wan_port_mappings",
        "columns": (
            "protocol",
            "external_port",
            "internal_client",
            "internal_port",
            "description",
            "enabled",
            "remote_host",
            "lease_duration",
            "source",
        ),
        "record_key_fields": ("protocol", "external_port", "internal_client", "internal_port", "source"),
        "sort": "COALESCE(t.external_port, '')",
        "time_column": "",
        "note": "WAN exposure/port mapping parsed from FRITZ!Box WAN connection evidence.",
    },
    "wlan_radios": {
        "dataset_keys": ("wlan_radios", "wlan_radio_details"),
        "record_type": "wlan_radio",
        "fts_type": "wlan_radios",
        "columns": (
            "radio_index",
            "ssid",
            "enabled",
            "status",
            "standard",
            "channel",
            "total_associations",
            "bytes_sent",
            "bytes_received",
            "source",
        ),
        "record_key_fields": ("radio_index", "ssid", "source"),
        "sort": "COALESCE(t.radio_index, '')",
        "time_column": "",
        "note": "WLAN radio state parsed from FRITZ!Box WLAN evidence.",
    },
    "wlan_associations": {
        "dataset_keys": ("wlan_associations", "wlan_association_details", "mesh_wifi_devices"),
        "record_type": "wlan_association",
        "fts_type": "wlan_associations",
        "columns": (
            "observed_at",
            "radio_index",
            "association_index",
            "mac",
            "ip",
            "hostname",
            "auth_state",
            "speed",
            "signal_strength",
            "channel",
            "guest",
            "source",
        ),
        "record_key_fields": ("observed_at", "radio_index", "association_index", "mac", "source"),
        "sort": "COALESCE(t.observed_at, '')",
        "time_column": "observed_at",
        "note": "Current WLAN association detail parsed from FRITZ!Box WLAN evidence; this is an observation, not a session start time.",
    },
    "advertisement_hints": {
        "dataset_keys": ("advertisement_hints", "broadcast_hints", "advertising_hints"),
        "record_type": "advertisement_hint",
        "fts_type": "advertisement_hints",
        "columns": (
            "observed_at",
            "hint_type",
            "protocol",
            "hostname",
            "mac",
            "ip",
            "direction",
            "confidence",
            "summary",
            "source",
        ),
        "record_key_fields": ("observed_at", "hint_type", "protocol", "mac", "ip", "source", "summary"),
        "sort": "COALESCE(t.observed_at, '')",
        "time_column": "observed_at",
        "note": (
            "Best-effort advertisement/broadcast hint from retained FRITZ!Box artifacts or router state; "
            "not packet-level proof of every broadcast."
        ),
    },
    "network_status_snapshots": {
        "dataset_keys": ("network_status_snapshots", "network_status", "network_counters"),
        "record_type": "network_status_snapshot",
        "fts_type": "network_status_snapshots",
        "columns": (
            "observed_at",
            "area",
            "metric",
            "value",
            "unit",
            "source",
            "confidence",
        ),
        "record_key_fields": ("observed_at", "area", "metric", "value", "source"),
        "sort": "COALESCE(t.observed_at, '')",
        "time_column": "observed_at",
        "note": "Network/WAN/DSL/LAN counter snapshot parsed from FRITZ!Box TR-064 evidence.",
    },
    "device_risk_summaries": {
        "dataset_keys": ("device_risk_summaries", "device_risks"),
        "record_type": "device_risk_summary",
        "fts_type": "device_risk_summaries",
        "columns": (
            "device_key",
            "hostname",
            "mac",
            "ip",
            "risk_level",
            "risk_score",
            "reasons_json",
            "summary",
            "source",
        ),
        "record_key_fields": ("device_key", "mac", "ip", "source"),
        "sort": "COALESCE(t.risk_score, '')",
        "time_column": "",
        "note": "Device risk summary derived from parsed FRITZ!Box host and exposure evidence.",
    },
    "security_advisories": {
        "dataset_keys": ("security_advisories", "security_audit_findings"),
        "record_type": "security_advisory",
        "fts_type": "security_advisories",
        "columns": (
            "advisory_id",
            "severity",
            "category",
            "title",
            "subject",
            "status",
            "recommendation",
            "source",
            "confidence",
            "evidence_json",
        ),
        "record_key_fields": ("advisory_id", "subject", "source"),
        "sort": "CASE t.severity WHEN 'critical' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END",
        "time_column": "",
        "note": "Security advisory derived from parsed FRITZ!Box settings and retained evidence; verify in raw artifacts before remediation.",
    },
    "wlan_station_state_snapshots": {
        "dataset_keys": ("wlan_station_state_snapshots",),
        "record_type": "wlan_station_state_snapshot",
        "fts_type": "wlan_station_state_snapshots",
        "columns": (
            "observed_at",
            "mac",
            "hostname",
            "ip",
            "interface",
            "bssid",
            "role_id",
            "connect_state",
            "active",
            "guest",
            "last_seen",
            "rssi",
            "quality",
            "speed",
            "source",
        ),
        "record_key_fields": ("observed_at", "mac", "interface", "bssid", "source"),
        "sort": "COALESCE(t.observed_at, '')",
        "time_column": "observed_at",
        "note": "Typed WLAN station state parsed from FRITZ!Box support/Web UI artifacts; snapshot data is not a complete session log.",
    },
    "wlan_station_intervals": {
        "dataset_keys": ("wlan_station_intervals",),
        "record_type": "wlan_station_interval",
        "fts_type": "wlan_station_intervals",
        "columns": (
            "connected_at",
            "disconnected_at",
            "mac",
            "interface",
            "role",
            "connect_status",
            "connect_initiator",
            "connect_reason",
            "disconnect_status",
            "disconnect_initiator",
            "disconnect_reason",
            "wlan_mode",
            "quality",
            "source",
        ),
        "record_key_fields": ("connected_at", "disconnected_at", "mac", "interface", "source"),
        "sort": "COALESCE(t.connected_at, '')",
        "time_column": "connected_at",
        "note": "Retained WLAN station-history interval parsed from support-data diagnostics.",
    },
    "wlan_ap_client_events": {
        "dataset_keys": ("wlan_ap_client_events",),
        "record_type": "wlan_ap_client_event",
        "fts_type": "wlan_ap_client_events",
        "columns": (
            "event_time",
            "event_kind",
            "mac",
            "interface",
            "reason_code",
            "status_code",
            "cipher",
            "session",
            "source",
            "message",
            "line_number",
        ),
        "record_key_fields": ("event_time", "event_kind", "mac", "interface", "line_number", "source"),
        "sort": "COALESCE(t.event_time, '')",
        "time_column": "event_time",
        "note": "AP-side WLAN client lifecycle event parsed from hostapd/support-data diagnostics.",
    },
    "wlan_event_details": {
        "dataset_keys": ("wlan_event_details",),
        "record_type": "wlan_event_detail",
        "fts_type": "wlan_event_details",
        "columns": (
            "event_time",
            "event_id",
            "mac",
            "interface",
            "band",
            "rate",
            "channel",
            "previous_channel",
            "details",
            "source",
        ),
        "record_key_fields": ("event_time", "event_id", "mac", "interface", "source"),
        "sort": "COALESCE(t.event_time, '')",
        "time_column": "event_time",
        "note": "Typed WLAN_EVENTS diagnostic row parsed from support-data.",
    },
    "dhcp_leases": {
        "dataset_keys": ("dhcp_leases",),
        "record_type": "dhcp_lease",
        "fts_type": "dhcp_leases",
        "columns": ("observed_at", "hostname", "mac", "ip", "lease_expires", "active", "source"),
        "record_key_fields": ("observed_at", "mac", "ip", "source"),
        "sort": "COALESCE(t.observed_at, '')",
        "time_column": "observed_at",
        "note": "DHCP/client lease context parsed from internal FRITZ!Box Web UI data.",
    },
    "aha_device_states": {
        "dataset_keys": ("aha_device_states",),
        "record_type": "aha_device_state",
        "fts_type": "aha_device_states",
        "columns": (
            "observed_at",
            "device_id",
            "name",
            "productname",
            "manufacturer",
            "functionbitmask",
            "state",
            "temperature",
            "humidity",
            "power",
            "energy",
            "source",
        ),
        "record_key_fields": ("observed_at", "device_id", "name", "source"),
        "sort": "COALESCE(t.observed_at, '')",
        "time_column": "observed_at",
        "note": "AHA/smart-home state parsed from FRITZ!Box AHA artifacts.",
    },
    "telephony_records": {
        "dataset_keys": ("telephony_records",),
        "record_type": "telephony_record",
        "fts_type": "telephony_records",
        "columns": (
            "observed_at",
            "record_type",
            "name",
            "number",
            "direction",
            "timestamp",
            "duration",
            "source",
        ),
        "record_key_fields": ("record_type", "name", "number", "timestamp", "source"),
        "sort": "COALESCE(t.timestamp, t.observed_at, '')",
        "time_column": "timestamp",
        "note": "Sensitive telephony metadata parsed from FRITZ!Box call-list/phonebook artifacts.",
    },
}
ADDITIONAL_RECORD_TYPE_ALIASES: dict[str, str] = {
    "host_filter": "host_filter_profiles",
    "host_filters": "host_filter_profiles",
    "host_filter_profiles": "host_filter_profiles",
    "mesh": "mesh_topology_links",
    "mesh_links": "mesh_topology_links",
    "mesh_topology": "mesh_topology_links",
    "mesh_topology_links": "mesh_topology_links",
    "wan": "wan_port_mappings",
    "wan_exposure": "wan_port_mappings",
    "port_mappings": "wan_port_mappings",
    "wan_port_mappings": "wan_port_mappings",
    "wlan_radios": "wlan_radios",
    "wlan_radio": "wlan_radios",
    "wlan_associations": "wlan_associations",
    "wlan_association": "wlan_associations",
    "advertisements": "advertisement_hints",
    "advertisement": "advertisement_hints",
    "advertisement_hints": "advertisement_hints",
    "advertising": "advertisement_hints",
    "broadcasts": "advertisement_hints",
    "broadcast_hints": "advertisement_hints",
    "network_status": "network_status_snapshots",
    "network_counters": "network_status_snapshots",
    "network_status_snapshots": "network_status_snapshots",
    "wan_stats": "network_status_snapshots",
    "dsl_stats": "network_status_snapshots",
    "lan_stats": "network_status_snapshots",
    "device_risks": "device_risk_summaries",
    "device_risk": "device_risk_summaries",
    "device_risk_summaries": "device_risk_summaries",
    "security": "security_advisories",
    "security_advisory": "security_advisories",
    "security_advisories": "security_advisories",
    "security_audit": "security_advisories",
    "security_audit_findings": "security_advisories",
    "wlan_station_state": "wlan_station_state_snapshots",
    "wlan_station_states": "wlan_station_state_snapshots",
    "wlan_station_state_snapshots": "wlan_station_state_snapshots",
    "wlan_station_intervals": "wlan_station_intervals",
    "wlan_station_interval": "wlan_station_intervals",
    "wlan_ap_client_events": "wlan_ap_client_events",
    "wlan_ap_client_event": "wlan_ap_client_events",
    "wlan_event_details": "wlan_event_details",
    "wlan_event_detail": "wlan_event_details",
    "dhcp": "dhcp_leases",
    "dhcp_leases": "dhcp_leases",
    "dhcp_lease": "dhcp_leases",
    "aha": "aha_device_states",
    "aha_device_states": "aha_device_states",
    "aha_device_state": "aha_device_states",
    "telephony": "telephony_records",
    "telephony_records": "telephony_records",
    "telephony_record": "telephony_records",
}
